### ISSUE TITLE
Add error treatment to apiBackends calls

### ISSUE THREAD

**Issue by mauriciovieira** [brylie/meteor-api-umbrella#1]
Nowadays, _apiUmbrellaWeb.adminApi.v1.apiBackends.createApiBackend(constructedBackend)_ does not treat errors. In case of failure https://github.com/brylie/meteor-api-umbrella/blob/master/server/admin-api/v1/apiBackends.js#L29 should treat the error and throw ApiUmbrellaError with the details.

For instance, _Error.message_ now is a string like `'failed [422] {"errors":{"backend_protocol":["is not included in the list"]}}'`. It should be a _ApiUmbrellaError_ with 

```
http_status: 422,
errors: {"backend_protocol":["is not included in the list"]}
```

along with the default _message_.
# Related documentation:
- [Error Handling in Node.js](https://www.joyent.com/developers/node/design/errors#4-augment-the--code-error--code--object-with-properties-that-explain-details)

**Comment by mauriciovieira** [comment]
@brylie I am looking into this now.

**Comment by brylie** [comment]
@mauriciovieira thanks. I can help repeat the basic pattern in the other API endpoints, once you have a working example for createApiBackend.

**Comment by mauriciovieira** [comment]
@brylie what I currently get using the same credentials of api-umbrella @ apinf.io and running _meteor --settings settings.json test-packages ./_ is ![screen shot 2015-11-09 at 8 49 43 am](https://cloud.githubusercontent.com/assets/95258/11031933/2e56ca1a-86bf-11e5-9485-7ea8dcbbf97d.png)

so I am now trying to set my local api-umbrella server to better debug the rails/node.js part.

**Comment by brylie** [comment]
Be sure to include a trailing slash in your `base_url` configuration.

**Comment by brylie** [comment]
Also, the backend changes may need to be published. We can do this via the [Admin API Config Publish endpoint](http://apiumbrella.io/docs/admin-api/#!/config/post_api_umbrella_v1_config_publish). Alternatively, this can be done via the API Umbrella admin UI.

**Comment by mauriciovieira** [comment]
@brylie The trailling slash is there.
At this point I think I don't need to publish the changes, I just want to get the errors.

**Comment by mauriciovieira** [comment]
For some reason, now I am getting the 422 error. This one is an umbrella's bug, but can be used to work with:
![screen shot 2015-11-11 at 8 08 23 am](https://cloud.githubusercontent.com/assets/95258/11088724/8adeeca8-884b-11e5-9ec6-6a9303e702c9.png)

**Comment by brylie** [comment]
Try working in my [development branch](https://github.com/brylie/meteor-api-umbrella/tree/feature/refactor-as-object).

**Comment by mauriciovieira** [comment]
@brylie I made some improvements with error handling on [mauriciovieira/meteor-api-umbrella:spike branch](https://github.com/mauriciovieira/meteor-api-umbrella/tree/spike)

See https://github.com/mauriciovieira/meteor-api-umbrella/blob/20d01fbd3283d5eb1e7cbbee5732aa481dd5ed4d/server/apiUmbrellaError.js

It is still not fully functional, but I believe I am in the correct path.

**Comment by brylie** [comment]
@mauriciovieira I have merged your pull request.

**Comment by Nazarah** [comment]
closing since the work related to this task has been merged as a PR
