### ISSUE TITLE
[Meta] Support all Admin API REST endpoints

### ISSUE THREAD

**Issue by brylie** [brylie/meteor-api-umbrella#2]
This package currently only supports a few of the Admin API endpoints. Add support for all methods and endpoints.

Related issue: Redesign Module API (#3)
# Task
- [ ] admin_group
- [ ] analytics
- [ ] admin_permission
- [ ] admin
- [ ] api_scope
- [ ] api
- [ ] config
- [ ] contact
- [ ] user_role
- [ ] user
- [ ] website_backend

**Comment by brylie** [comment]
It may be worth considering deprecating this integration package entirely. There is a SwaggerJS integration for Meteor that takes a swagger.json file and creates a JS object to interact with the API.

**Comment by Nazarah** [comment]
closing this.
