### ISSUE TITLE
Fix configurationTests

### ISSUE THREAD

**Issue by mauriciovieira** [brylie/meteor-api-umbrella#5]
![screencapture-localhost-3000-1447407954592](https://cloud.githubusercontent.com/assets/95258/11143210/a121e124-89da-11e5-9e32-b532be0ed47a.png)

**Comment by mauriciovieira** [comment]
@brylie I am working on this now.

**Comment by mauriciovieira** [comment]
@brylie I did some work on https://github.com/mauriciovieira/meteor-api-umbrella/commit/70257b2476eefe50898a6965543ef7df7271aac8 but some tests still have to be fixed.

![screencapture-localhost-3000-1447415815086](https://cloud.githubusercontent.com/assets/95258/11145509/436475c0-89ed-11e5-9a0f-4aae95ae80d8.png)

**Comment by brylie** [comment]
OK, thanks.

**Comment by mauriciovieira** [comment]
@brylie As I am getting a 403 from the rails backend, I think the interface is now ok.

There were some typo changes needed, in order to make the client to function. 

![screencapture-localhost-3000-1447675243412](https://cloud.githubusercontent.com/assets/95258/11181420/08661c18-8c49-11e5-98eb-d545b57d8cba.png)

**Comment by mauriciovieira** [comment]
@brylie All ok, now.

![screencapture-localhost-3000-1447720166022](https://cloud.githubusercontent.com/assets/95258/11199095/9d0f68f2-8cb1-11e5-92a2-97b4df8d0744.png)
